# -*- coding: utf-8 -*-
"""公司池配置：双创科技赛道前 150 家（科创板 75 + 创业板 75）

数据源切换为腾讯证券自选股后端（qt.gtimg.cn 报价 + web.ifzq.gtimg.cn 日线）。
公司池为手工精选的双创（创业板指 + 科创板指）科技公司，按科技口径（半导体 /
软件 / 通信 / 高端制造 / 新能源 / 医疗科技 / 新材料 / 军工电子 等）筛选。

字段说明：
    code        股票代码（6 位）
    name        公司简称
    board       板块（科创板 / 创业板）
    industry    一级行业 / 细分领域
    business    核心业务描述（业务题正确答案）
    hot_correct 热点题正确答案（必须在 HOT_TOPICS 里）

干扰项（distractors）与热点选项（hot_options）由 server.build_quiz 在
出题时从 DISTRACTOR_POOL / HOT_TOPICS 动态随机生成，避免文件冗余。
"""

# 热点主题池：热点题的 4 选项将从这里抽（含正确答案）
HOT_TOPICS = [
    "AI算力", "AI大模型", "芯片国产化", "国产替代", "国产算力",
    "新能源", "储能", "光伏", "半导体", "半导体设备",
    "机器人", "军工", "金融科技", "医疗器械", "消费电子",
    "信创", "光通信", "数据要素", "低空经济", "创新药",
    "疫苗", "医疗IT", "网络安全", "智能汽车", "卫星互联网",
    "半导体材料", "服务器", "电力设备", "工业软件", "PCB",
    "物联网",
]

# 业务干扰项池：业务题的 3 个干扰项从这里随机抽取
DISTRACTOR_POOL = [
    "动力电池研发制造", "光伏组件生产", "工业机器人整机", "消费电子代工",
    "光纤通信器件制造", "面板驱动 IC 设计", "通用 CPU 设计", "存储芯片制造",
    "汽车 MCU 设计", "光刻胶生产", "硅片制造", "封装测试代工",
    "风电整机装备", "氢燃料电池系统", "光伏逆变器制造", "疫苗研发生产",
    "创新药研发生产", "连锁医院经营", "PCB 制造", "连接器制造",
    "显示模组组装", "通信基站建设", "光纤预制棒生产", "齿科连锁经营",
    "医美器械制造", "血液透析设备", "体外诊断试剂生产", "心脏支架生产",
    "数控机床制造", "电源管理芯片设计", "光模块研发制造", "硅料生产",
    "电池片制造", "基带芯片设计", "网游研发运营", "影视制作发行",
    "保险经纪服务", "公募基金管理", "饲料生产加工", "工程机械整机",
    "智能电表制造", "MLCC 陶瓷制造", "存储主控芯片设计", "GPU 设计",
    "IGBT 功率器件", "AI 大模型训练", "公有云服务运营", "网络安全设备制造",
    "工业软件研发", "金融信息软件", "动力电池回收", "储能变流器制造",
    "数据湖存储建设", "工业互联网平台", "生物可降解材料", "LCP 高分子材料",
    "碳纤维原丝生产", "靶材研发制造", "ITO 透明导电玻璃", "电子级环氧塑封料",
]


COMPANIES = [
    # ==================== 科创板 75 家 ====================
    {"code": "688005", "name": "容百科技", "board": "科创板", "industry": "新能源",
     "business": "三元正极材料研发制造", "hot_correct": "新能源"},
    {"code": "688006", "name": "杭可科技", "board": "科创板", "industry": "锂电设备",
     "business": "锂电池后处理自动化装备", "hot_correct": "新能源"},
    {"code": "688007", "name": "光峰科技", "board": "科创板", "industry": "光学显示",
     "business": "激光显示光源与整机", "hot_correct": "消费电子"},
    {"code": "688008", "name": "澜起科技", "board": "科创板", "industry": "半导体",
     "business": "内存接口与缓冲芯片设计", "hot_correct": "AI算力"},
    {"code": "688011", "name": "新光光电", "board": "科创板", "industry": "军工光学",
     "business": "光学制导与光电瞄准设备", "hot_correct": "军工"},
    {"code": "688012", "name": "中微公司", "board": "科创板", "industry": "半导体设备",
     "business": "半导体刻蚀与 MOCVD 设备", "hot_correct": "半导体设备"},
    {"code": "688016", "name": "心脉医疗", "board": "科创板", "industry": "医疗器械",
     "business": "主动脉与外周血管介入器械", "hot_correct": "医疗器械"},
    {"code": "688017", "name": "绿的谐波", "board": "科创板", "industry": "机器人",
     "business": "精密谐波减速器研发制造", "hot_correct": "机器人"},
    {"code": "688018", "name": "乐鑫科技", "board": "科创板", "industry": "半导体",
     "business": "Wi-Fi / 蓝牙 AIoT MCU 芯片", "hot_correct": "芯片国产化"},
    {"code": "688019", "name": "安集科技", "board": "科创板", "industry": "半导体材料",
     "business": "CMP 抛光液与半导体材料", "hot_correct": "半导体材料"},
    {"code": "688022", "name": "晶晨股份", "board": "科创板", "industry": "半导体",
     "business": "智能机顶盒与电视 SoC 芯片", "hot_correct": "芯片国产化"},
    {"code": "688023", "name": "安恒信息", "board": "科创板", "industry": "网络安全",
     "business": "云安全与网络信息安全产品", "hot_correct": "网络安全"},
    {"code": "688027", "name": "国盾量子", "board": "科创板", "industry": "量子科技",
     "business": "量子保密通信设备", "hot_correct": "信创"},
    {"code": "688030", "name": "山石网科", "board": "科创板", "industry": "网络安全",
     "business": "网络安全硬件与边界防护", "hot_correct": "网络安全"},
    {"code": "688036", "name": "传音控股", "board": "科创板", "industry": "消费电子",
     "business": "面向新兴市场的智能手机", "hot_correct": "消费电子"},
    {"code": "688037", "name": "芯源微", "board": "科创板", "industry": "半导体设备",
     "business": "涂胶显影与清洗设备", "hot_correct": "半导体设备"},
    {"code": "688041", "name": "海光信息", "board": "科创板", "industry": "半导体",
     "business": "国产 CPU / DCU 处理器", "hot_correct": "国产算力"},
    {"code": "688083", "name": "中望软件", "board": "科创板", "industry": "工业软件",
     "business": "工业 CAD / CAE 软件研发", "hot_correct": "工业软件"},
    {"code": "688100", "name": "威高信息", "board": "科创板", "industry": "医疗IT",
     "business": "临床信息管理与智慧医疗软件", "hot_correct": "医疗IT"},
    {"code": "688111", "name": "金山办公", "board": "科创板", "industry": "软件",
     "business": "WPS 办公软件与协作服务", "hot_correct": "信创"},
    {"code": "688116", "name": "天奈科技", "board": "科创板", "industry": "新材料",
     "business": "碳纳米管导电浆料", "hot_correct": "新能源"},
    {"code": "688122", "name": "西部超导", "board": "科创板", "industry": "新材料",
     "business": "高端钛合金与超导线材", "hot_correct": "军工"},
    {"code": "688126", "name": "沪硅产业", "board": "科创板", "industry": "半导体材料",
     "business": "300mm 半导体大硅片", "hot_correct": "半导体材料"},
    {"code": "688138", "name": "清溢光电", "board": "科创板", "industry": "半导体材料",
     "business": "掩膜版与精密光罩", "hot_correct": "半导体材料"},
    {"code": "688159", "name": "有方科技", "board": "科创板", "industry": "物联网",
     "business": "物联网无线通信模块", "hot_correct": "物联网"},
    {"code": "688165", "name": "埃夫特", "board": "科创板", "industry": "机器人",
     "business": "工业机器人整机与产线", "hot_correct": "机器人"},
    {"code": "688169", "name": "石头科技", "board": "科创板", "industry": "服务机器人",
     "business": "智能扫地机器人", "hot_correct": "机器人"},
    {"code": "688170", "name": "安博通", "board": "科创板", "industry": "网络安全",
     "business": "网络安全可视化与策略软件", "hot_correct": "网络安全"},
    {"code": "688173", "name": "瑞松科技", "board": "科创板", "industry": "机器人",
     "business": "智能制造与焊接机器人产线", "hot_correct": "机器人"},
    {"code": "688185", "name": "康希诺", "board": "科创板", "industry": "疫苗",
     "business": "创新疫苗研发与生产", "hot_correct": "疫苗"},
    {"code": "688187", "name": "时代电气", "board": "科创板", "industry": "功率半导体",
     "business": "IGBT 与轨交功率器件", "hot_correct": "半导体"},
    {"code": "688188", "name": "柏楚电子", "board": "科创板", "industry": "激光",
     "business": "激光切割控制系统", "hot_correct": "国产替代"},
    {"code": "688190", "name": "云路股份", "board": "科创板", "industry": "新材料",
     "business": "非晶 / 纳米晶软磁材料", "hot_correct": "电力设备"},
    {"code": "688197", "name": "首药控股", "board": "科创板", "industry": "创新药",
     "business": "抗肿瘤小分子创新药", "hot_correct": "创新药"},
    {"code": "688198", "name": "佰仁医疗", "board": "科创板", "industry": "医疗器械",
     "business": "心脏瓣膜介入器械", "hot_correct": "医疗器械"},
    {"code": "688200", "name": "华峰测控", "board": "科创板", "industry": "半导体设备",
     "business": "半导体模拟测试系统", "hot_correct": "半导体设备"},
    {"code": "688202", "name": "美迪西", "board": "科创板", "industry": "CRO服务",
     "business": "医药研发外包 CRO 服务", "hot_correct": "创新药"},
    {"code": "688215", "name": "瑞晟智能", "board": "科创板", "industry": "智能物流",
     "business": "智能分拣与物流输送系统", "hot_correct": "机器人"},
    {"code": "688225", "name": "亚信安全", "board": "科创板", "industry": "网络安全",
     "business": "终端安全与威胁防护软件", "hot_correct": "网络安全"},
    {"code": "688228", "name": "翱捷科技", "board": "科创板", "industry": "半导体",
     "business": "基带芯片与智能 SoC", "hot_correct": "芯片国产化"},
    {"code": "688235", "name": "百济神州", "board": "科创板", "industry": "创新药",
     "business": "抗肿瘤创新药全球研发", "hot_correct": "创新药"},
    {"code": "688251", "name": "井松智能", "board": "科创板", "industry": "智能物流",
     "business": "智能立体仓库与 AGV", "hot_correct": "机器人"},
    {"code": "688256", "name": "寒武纪", "board": "科创板", "industry": "AI芯片",
     "business": "云端 / 边缘 AI 加速芯片", "hot_correct": "AI算力"},
    {"code": "688259", "name": "创耀科技", "board": "科创板", "industry": "半导体",
     "business": "接入网与工业通信芯片", "hot_correct": "芯片国产化"},
    {"code": "688262", "name": "国博电子", "board": "科创板", "industry": "军工电子",
     "business": "有源相控阵 T/R 组件", "hot_correct": "军工"},
    {"code": "688526", "name": "科前生物", "board": "科创板", "industry": "动物保健",
     "business": "动物疫苗与诊断试剂", "hot_correct": "疫苗"},
    {"code": "688265", "name": "南亚新材", "board": "科创板", "industry": "电子材料",
     "business": "高频高速覆铜板", "hot_correct": "国产替代"},
    {"code": "688268", "name": "华秦科技", "board": "科创板", "industry": "军工材料",
     "business": "隐身 / 防护涂层材料", "hot_correct": "军工"},
    {"code": "688278", "name": "奥特维", "board": "科创板", "industry": "高端装备",
     "business": "锂电与光伏自动化装备", "hot_correct": "半导体设备"},
    {"code": "688280", "name": "国能日新", "board": "科创板", "industry": "软件",
     "business": "新能源发电信息化软件", "hot_correct": "新能源"},
    {"code": "688283", "name": "长盈通", "board": "科创板", "industry": "光电子",
     "business": "光纤陀螺与光纤环器件", "hot_correct": "军工"},
    {"code": "688286", "name": "华大智造", "board": "科创板", "industry": "医疗器械",
     "business": "基因测序仪研发制造", "hot_correct": "医疗器械"},
    {"code": "688298", "name": "东方生物", "board": "科创板", "industry": "体外诊断",
     "business": "POCT 快速诊断产品", "hot_correct": "医疗器械"},
    {"code": "688303", "name": "大全能源", "board": "科创板", "industry": "光伏材料",
     "business": "高纯多晶硅生产", "hot_correct": "光伏"},
    {"code": "688305", "name": "科德数控", "board": "科创板", "industry": "高端装备",
     "business": "五轴联动数控机床", "hot_correct": "国产替代"},
    {"code": "688326", "name": "经纬恒润", "board": "科创板", "industry": "汽车电子",
     "business": "汽车电子系统与控制器", "hot_correct": "智能汽车"},
    {"code": "688330", "name": "宏力达", "board": "科创板", "industry": "电力设备",
     "business": "配电网智能开关", "hot_correct": "电力设备"},
    {"code": "688335", "name": "复旦微电", "board": "科创板", "industry": "半导体",
     "business": "FPGA 与安全识别芯片", "hot_correct": "芯片国产化"},
    {"code": "688337", "name": "普源精电", "board": "科创板", "industry": "仪器仪表",
     "business": "通用电子测量仪器", "hot_correct": "国产替代"},
    {"code": "688348", "name": "昱能科技", "board": "科创板", "industry": "光伏储能",
     "business": "光伏微型逆变器与关断器", "hot_correct": "储能"},
    {"code": "688357", "name": "中复神鹰", "board": "科创板", "industry": "新材料",
     "business": "高性能碳纤维", "hot_correct": "军工"},
    {"code": "688363", "name": "华熙生物", "board": "科创板", "industry": "生物科技",
     "business": "透明质酸原料与终端产品", "hot_correct": "医疗器械"},
    {"code": "688368", "name": "晶丰明源", "board": "科创板", "industry": "半导体",
     "business": "LED 照明驱动与电源芯片", "hot_correct": "芯片国产化"},
    {"code": "688385", "name": "山外山", "board": "科创板", "industry": "医疗器械",
     "business": "血液净化设备与耗材", "hot_correct": "医疗器械"},
    {"code": "688390", "name": "固德威", "board": "科创板", "industry": "光伏储能",
     "business": "光伏储能逆变器", "hot_correct": "储能"},
    {"code": "688408", "name": "中信博", "board": "科创板", "industry": "光伏设备",
     "business": "光伏跟踪支架系统", "hot_correct": "光伏"},
    {"code": "688439", "name": "星环科技", "board": "科创板", "industry": "软件",
     "business": "大数据与云基础软件", "hot_correct": "数据要素"},
    {"code": "688472", "name": "希荻微", "board": "科创板", "industry": "半导体",
     "business": "电源管理与音频芯片", "hot_correct": "芯片国产化"},
    {"code": "688567", "name": "孚能科技", "board": "科创板", "industry": "动力电池",
     "business": "软包动力电池电芯", "hot_correct": "新能源"},
    {"code": "688639", "name": "华海诚科", "board": "科创板", "industry": "半导体材料",
     "business": "电子级环氧塑封料", "hot_correct": "半导体材料"},
    {"code": "688728", "name": "格科微", "board": "科创板", "industry": "半导体",
     "business": "CMOS 图像传感器芯片", "hot_correct": "消费电子"},
    {"code": "688777", "name": "中大力德", "board": "科创板", "industry": "机器人",
     "business": "精密减速器与传动件", "hot_correct": "机器人"},
    {"code": "688787", "name": "海天瑞声", "board": "科创板", "industry": "AI数据",
     "business": "AI 训练数据与标注服务", "hot_correct": "AI大模型"},
    {"code": "688798", "name": "艾为电子", "board": "科创板", "industry": "半导体",
     "business": "模拟与射频前端芯片", "hot_correct": "芯片国产化"},
    {"code": "688981", "name": "中芯国际", "board": "科创板", "industry": "半导体",
     "business": "集成电路晶圆代工与技术服务", "hot_correct": "芯片国产化"},

    # ==================== 创业板 75 家 ====================
    {"code": "300003", "name": "乐普医疗", "board": "创业板", "industry": "医疗器械",
     "business": "心血管支架与介入器械", "hot_correct": "医疗器械"},
    {"code": "300015", "name": "爱尔眼科", "board": "创业板", "industry": "医疗服务",
     "business": "眼科医疗连锁服务", "hot_correct": "医疗IT"},
    {"code": "300017", "name": "网宿科技", "board": "创业板", "industry": "互联网",
     "business": "CDN 与边缘计算服务", "hot_correct": "AI算力"},
    {"code": "300024", "name": "机器人", "board": "创业板", "industry": "机器人",
     "business": "工业机器人本体与产线", "hot_correct": "机器人"},
    {"code": "300033", "name": "同花顺", "board": "创业板", "industry": "金融科技",
     "business": "金融行情与资讯软件", "hot_correct": "金融科技"},
    {"code": "300034", "name": "钢研高纳", "board": "创业板", "industry": "新材料",
     "business": "高温合金与铸造母合金", "hot_correct": "军工"},
    {"code": "300037", "name": "新宙邦", "board": "创业板", "industry": "新能源",
     "business": "锂电池电解液与精细氟化工", "hot_correct": "新能源"},
    {"code": "300059", "name": "东方财富", "board": "创业板", "industry": "非银金融",
     "business": "互联网证券与基金销售平台", "hot_correct": "金融科技"},
    {"code": "300065", "name": "海兰信", "board": "创业板", "industry": "海洋科技",
     "business": "海洋电子与智能航海装备", "hot_correct": "国产替代"},
    {"code": "300073", "name": "当升科技", "board": "创业板", "industry": "新能源",
     "business": "锂电正极材料研发", "hot_correct": "新能源"},
    {"code": "300075", "name": "数字政通", "board": "创业板", "industry": "软件",
     "business": "智慧城市与数字化治理软件", "hot_correct": "数据要素"},
    {"code": "300077", "name": "国民技术", "board": "创业板", "industry": "半导体",
     "business": "安全芯片与 RISC-V MCU", "hot_correct": "芯片国产化"},
    {"code": "300088", "name": "长信科技", "board": "创业板", "industry": "电子",
     "business": "触控显示器件与模组", "hot_correct": "消费电子"},
    {"code": "300101", "name": "振芯科技", "board": "创业板", "industry": "半导体",
     "business": "北斗与视频处理芯片", "hot_correct": "卫星互联网"},
    {"code": "300115", "name": "长盈精密", "board": "创业板", "industry": "消费电子",
     "business": "消费电子精密结构件", "hot_correct": "消费电子"},
    {"code": "300118", "name": "东方日升", "board": "创业板", "industry": "光伏",
     "business": "光伏组件与系统集成", "hot_correct": "光伏"},
    {"code": "300124", "name": "汇川技术", "board": "创业板", "industry": "工控",
     "business": "工业自动化与新能源汽车电控", "hot_correct": "机器人"},
    {"code": "300136", "name": "信维通信", "board": "创业板", "industry": "消费电子",
     "business": "移动终端天线与射频", "hot_correct": "消费电子"},
    {"code": "300142", "name": "沃森生物", "board": "创业板", "industry": "疫苗",
     "business": "人用疫苗研发与生产", "hot_correct": "疫苗"},
    {"code": "300168", "name": "万达信息", "board": "创业板", "industry": "医疗IT",
     "business": "医疗信息化与政务软件", "hot_correct": "医疗IT"},
    {"code": "300170", "name": "汉得信息", "board": "创业板", "industry": "IT服务",
     "business": "企业 IT 咨询与实施", "hot_correct": "信创"},
    {"code": "300177", "name": "中海达", "board": "创业板", "industry": "北斗",
     "business": "北斗高精度测绘装备", "hot_correct": "卫星互联网"},
    {"code": "300185", "name": "通裕重工", "board": "创业板", "industry": "高端装备",
     "business": "风电主轴与海工装备", "hot_correct": "国产替代"},
    {"code": "300188", "name": "美亚柏科", "board": "创业板", "industry": "网络安全",
     "business": "电子数据取证与大数据", "hot_correct": "网络安全"},
    {"code": "300212", "name": "易华录", "board": "创业板", "industry": "数据要素",
     "business": "数据湖与光存储建设", "hot_correct": "数据要素"},
    {"code": "300223", "name": "北京君正", "board": "创业板", "industry": "半导体",
     "business": "CPU / DRAM 与微处理器", "hot_correct": "芯片国产化"},
    {"code": "300236", "name": "上海新阳", "board": "创业板", "industry": "半导体材料",
     "business": "半导体化学与电镀液", "hot_correct": "半导体材料"},
    {"code": "300244", "name": "润和软件", "board": "创业板", "industry": "软件",
     "business": "软件服务与鸿蒙生态", "hot_correct": "信创"},
    {"code": "300247", "name": "智云股份", "board": "创业板", "industry": "锂电设备",
     "business": "锂电池智能制造装备", "hot_correct": "新能源"},
    {"code": "300253", "name": "卫宁健康", "board": "创业板", "industry": "医疗IT",
     "business": "医院信息化与互联网医疗", "hot_correct": "医疗IT"},
    {"code": "300274", "name": "阳光电源", "board": "创业板", "industry": "光伏储能",
     "business": "光伏逆变器与储能变流器", "hot_correct": "储能"},
    {"code": "300285", "name": "国瓷材料", "board": "创业板", "industry": "新材料",
     "business": "MLCC 陶瓷与牙科材料", "hot_correct": "半导体材料"},
    {"code": "300296", "name": "利亚德", "board": "创业板", "industry": "LED",
     "business": "小间距 LED 显示与会议屏", "hot_correct": "消费电子"},
    {"code": "300308", "name": "中际旭创", "board": "创业板", "industry": "光通信",
     "business": "高速光模块（800G / 1.6T）", "hot_correct": "AI算力"},
    {"code": "300316", "name": "晶盛机电", "board": "创业板", "industry": "高端装备",
     "business": "半导体与光伏长晶设备", "hot_correct": "半导体设备"},
    {"code": "300327", "name": "中颖电子", "board": "创业板", "industry": "半导体",
     "business": "家电与 AMOLED 显示 MCU", "hot_correct": "芯片国产化"},
    {"code": "300346", "name": "南大光电", "board": "创业板", "industry": "半导体材料",
     "business": "MO 源与前驱体、光刻胶", "hot_correct": "半导体材料"},
    {"code": "300353", "name": "东土科技", "board": "创业板", "industry": "工业互联网",
     "business": "工业以太网与控制服务器", "hot_correct": "工业软件"},
    {"code": "300369", "name": "绿盟科技", "board": "创业板", "industry": "网络安全",
     "business": "网络安全产品与服务", "hot_correct": "网络安全"},
    {"code": "300376", "name": "易事特", "board": "创业板", "industry": "电力电子",
     "business": "UPS 电源与数据中心能源", "hot_correct": "AI算力"},
    {"code": "300383", "name": "光环新网", "board": "创业板", "industry": "数据中心",
     "business": "数据中心 IDC 与云计算", "hot_correct": "AI算力"},
    {"code": "300394", "name": "天孚通信", "board": "创业板", "industry": "光通信",
     "business": "光通信器件与无源器件", "hot_correct": "光通信"},
    {"code": "300398", "name": "飞凯材料", "board": "创业板", "industry": "半导体材料",
     "business": "半导体封装与显示材料", "hot_correct": "半导体材料"},
    {"code": "300408", "name": "三环集团", "board": "创业板", "industry": "电子元件",
     "business": "电子陶瓷与光通信零件", "hot_correct": "消费电子"},
    {"code": "300418", "name": "昆仑万维", "board": "创业板", "industry": "AI",
     "business": "AI 大模型与社交游戏", "hot_correct": "AI大模型"},
    {"code": "300433", "name": "蓝思科技", "board": "创业板", "industry": "消费电子",
     "business": "玻璃 / 金属外观件与组装", "hot_correct": "消费电子"},
    {"code": "300451", "name": "创业慧康", "board": "创业板", "industry": "医疗IT",
     "business": "医院信息化与区域卫生平台", "hot_correct": "医疗IT"},
    {"code": "300454", "name": "深信服", "board": "创业板", "industry": "网络安全",
     "business": "网络安全与云计算/超融合", "hot_correct": "网络安全"},
    {"code": "300458", "name": "全志科技", "board": "创业板", "industry": "半导体",
     "business": "智能应用处理器 SoC", "hot_correct": "芯片国产化"},
    {"code": "300474", "name": "景嘉微", "board": "创业板", "industry": "半导体",
     "business": "国产 GPU 与图形显控", "hot_correct": "国产算力"},
    {"code": "300502", "name": "新易盛", "board": "创业板", "industry": "光通信",
     "business": "高速光模块与有源光缆", "hot_correct": "AI算力"},
    {"code": "300529", "name": "健帆生物", "board": "创业板", "industry": "医疗器械",
     "business": "血液灌流器与吸附耗材", "hot_correct": "医疗器械"},
    {"code": "300598", "name": "诚迈科技", "board": "创业板", "industry": "软件",
     "business": "智能操作系统与鸿蒙生态", "hot_correct": "信创"},
    {"code": "300602", "name": "飞荣达", "board": "创业板", "industry": "电子材料",
     "business": "电磁屏蔽与热管理材料", "hot_correct": "AI算力"},
    {"code": "300604", "name": "长川科技", "board": "创业板", "industry": "半导体设备",
     "business": "半导体测试与分选设备", "hot_correct": "半导体设备"},
    {"code": "300613", "name": "富瀚微", "board": "创业板", "industry": "半导体",
     "business": "视频监控与安防芯片", "hot_correct": "芯片国产化"},
    {"code": "300620", "name": "光库科技", "board": "创业板", "industry": "光通信",
     "business": "光纤器件与铌酸锂调制器", "hot_correct": "光通信"},
    {"code": "300623", "name": "捷捷微电", "board": "创业板", "industry": "功率半导体",
     "business": "晶闸管与功率半导体器件", "hot_correct": "半导体"},
    {"code": "300627", "name": "华测导航", "board": "创业板", "industry": "北斗",
     "business": "北斗高精度测绘与位移监测", "hot_correct": "卫星互联网"},
    {"code": "300633", "name": "开立医疗", "board": "创业板", "industry": "医疗器械",
     "business": "超声与消化内镜系统", "hot_correct": "医疗器械"},
    {"code": "300661", "name": "圣邦股份", "board": "创业板", "industry": "半导体",
     "business": "模拟芯片（电源管理/信号链）", "hot_correct": "芯片国产化"},
    {"code": "300666", "name": "江丰电子", "board": "创业板", "industry": "半导体材料",
     "business": "高纯溅射靶材研发制造", "hot_correct": "半导体材料"},
    {"code": "300676", "name": "华大基因", "board": "创业板", "industry": "基因科技",
     "business": "基因测序与生育健康服务", "hot_correct": "医疗器械"},
    {"code": "300707", "name": "雅克科技", "board": "创业板", "industry": "半导体材料",
     "business": "半导体前驱体与光刻胶", "hot_correct": "半导体材料"},
    {"code": "300720", "name": "拓斯达", "board": "创业板", "industry": "机器人",
     "business": "工业机器人与自动化解决方案", "hot_correct": "机器人"},
    {"code": "300738", "name": "奥飞数据", "board": "创业板", "industry": "数据中心",
     "business": "IDC 数据中心与云计算", "hot_correct": "AI算力"},
    {"code": "300749", "name": "顶点软件", "board": "创业板", "industry": "金融科技",
     "business": "金融行业 IT 软件与中台", "hot_correct": "金融科技"},
    {"code": "300750", "name": "宁德时代", "board": "创业板", "industry": "电力设备",
     "business": "动力电池与储能系统研发制造", "hot_correct": "新能源"},
    {"code": "300759", "name": "康泰生物", "board": "创业板", "industry": "疫苗",
     "business": "人用疫苗研发与生产", "hot_correct": "疫苗"},
    {"code": "300760", "name": "迈瑞医疗", "board": "创业板", "industry": "医疗器械",
     "business": "生命信息支持与体外诊断、影像", "hot_correct": "医疗器械"},
    {"code": "300768", "name": "迪普科技", "board": "创业板", "industry": "网络安全",
     "business": "网络安全与应用交付硬件", "hot_correct": "网络安全"},
    {"code": "300777", "name": "中简科技", "board": "创业板", "industry": "新材料",
     "business": "高性能碳纤维研发", "hot_correct": "军工"},
    {"code": "300782", "name": "卓胜微", "board": "创业板", "industry": "半导体",
     "business": "射频前端芯片（滤波器/开关）", "hot_correct": "芯片国产化"},
    {"code": "300866", "name": "安克创新", "board": "创业板", "industry": "消费电子",
     "business": "Anker 智能硬件与充电消费电子", "hot_correct": "消费电子"},
    {"code": "301160", "name": "德明利", "board": "创业板", "industry": "半导体",
     "business": "存储主控芯片与存储模组", "hot_correct": "芯片国产化"},
]


def all_codes():
    """返回去重后的代码列表"""
    seen, out = set(), []
    for c in COMPANIES:
        if c["code"] not in seen:
            seen.add(c["code"])
            out.append(c)
    return out


# 启动时打印校验
if __name__ == "__main__":
    codes = [c["code"] for c in COMPANIES]
    print(f"公司总数：{len(COMPANIES)}")
    print(f"代码去重后：{len(set(codes))}")
    print(f"科创板：{sum(1 for c in COMPANIES if c['board']=='科创板')}")
    print(f"创业板：{sum(1 for c in COMPANIES if c['board']=='创业板')}")
    print(f"hot_correct 不在 HOT_TOPICS："
          f"{[c['name'] for c in COMPANIES if c['hot_correct'] not in HOT_TOPICS]}")
